### ISSUE TITLE
otto code generation

### ISSUE THREAD

**Issue by peterbollen** [pyricau/CleanAndroidCode#10]
Hi,

is there a reason why you're using a otto version that uses code generation instead of reflection? Would it be possible to use the normal version instead, i.e. 1.3.4? 

As I'm experiencing dupes during installing of subscribers. As a consequence the same event gets delivered twice.

Greetings,
Peter

**Comment by pyricau** [comment]
I wrote this demo project a year ago, where the otto with code generation was supposed to come out soon and I wanted to get these things to work together. I don't know anything about how to make all of this work together today.
